default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: trackster_development

test:
  <<: *default
  database: trackster_test

production:
  <<: *default
  database: trackster_production
  username: trackster
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
